function A = A_rimless_wheel_3_spoke(in1,in2)
%A_rimless_wheel_3_spoke
%    A = A_rimless_wheel_3_spoke(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

I = in2(3,:);
Il = in2(11,:);
Im = in2(12,:);
M = in2(1,:);
R = in2(10,:);
t2 = R.^2;
t3 = Il.*t2;
t4 = Im+t3;
A = reshape([M,0.0,0.0,0.0,0.0,0.0,0.0,M,0.0,0.0,0.0,0.0,0.0,0.0,I,0.0,0.0,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,t4],[6,6]);
end
