function b = b_rimless_wheel_3_spoke(in1,in2)
%B_RIMLESS_WHEEL_3_SPOKE
%    B = B_RIMLESS_WHEEL_3_SPOKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

M = in2(1,:);
g = in2(5,:);
ramp = in2(6,:);
b = [M.*g.*sin(ramp);-M.*g.*cos(ramp);0.0;0.0;0.0;0.0];
end
