function ddq_0_q = ddq_0_q(in1,in2)
%DDQ_0_Q
%    DDQ_0_Q = DDQ_0_Q(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:52:04

ddq_0_q = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
end
