function ddq_0 = ddq_0(in1,in2,in3)
%DDQ_0
%    DDQ_0 = DDQ_0(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:52:04

Il = in2(11,:);
Im = in2(12,:);
R = in2(10,:);
g = in2(5,:);
ramp = in2(6,:);
uA = in3(1,:);
uB = in3(2,:);
uF = in3(3,:);
t2 = R.^2;
t3 = Il.*t2;
t4 = Im+t3;
t5 = 1.0./t4;
ddq_0 = [g.*sin(ramp);-g.*cos(ramp);0.0;t5.*uA;t5.*uB;t5.*uF];
end
