function ddq_A = ddq_A(in1,in2,in3)
%ddq_A
%    ddq_A = ddq_A(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-May-2025 17:01:31

I = in2(3,:);
Il = in2(11,:);
Im = in2(12,:);
M = in2(1,:);
R = in2(10,:);
dpsiA = in1(10,:);
dth = in1(9,:);
dx = in1(7,:);
dy = in1(8,:);
g = in2(5,:);
l = in2(4,:);
l0 = in2(8,:);
psiA = in1(4,:);
r = in2(9,:);
ramp = in2(6,:);
th = in1(3,:);
uA = in3(1,:);
uB = in3(2,:);
uF = in3(3,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = R.^2;
t5 = R.*psiA.*r;
t6 = 1.0./M;
t9 = dx.*1.0e+3;
t7 = Il.*t4;
t8 = R.*dpsiA.*r.*t2;
t11 = l+l0+t5;
t15 = R.*dpsiA.*r.*t3.*1.0e+3;
t10 = Im+t7;
t12 = -t8;
t13 = t2.*t11;
t16 = dth.*t3.*t11;
t14 = 1.0./t10;
t17 = -t13;
t20 = dth.*t13.*1.0e+3;
t21 = pi.*(t13-y).*-5.0;
t23 = dy+t12+t16;
t18 = t17+y;
t22 = tan(t21);
t25 = t9+t15+t20;
t19 = abs(t18);
t24 = t22.*1.0e+2;
t26 = atan(t25);
t27 = t19.*t23.*5.0e+3;
t28 = t24+t27;
ddq_A = [t6.*(t26.*t28.*5.092958178940651e-1+M.*g.*sin(ramp));-t6.*(t28+M.*g.*cos(ramp));-(t3.*t11.*t28-t13.*t26.*t28.*5.092958178940651e-1)./I;t14.*(uA+R.*r.*t2.*t28+R.*r.*t3.*t26.*t28.*5.092958178940651e-1);t14.*uB;t14.*uF];
end
