function ddq_AF_u = ddq_AF_u(in1,in2)
%ddq_AF_u
%    ddq_AF_u = ddq_AF_u(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 15:20:17

Il = in2(11,:);
Im = in2(12,:);
R = in2(10,:);
t2 = R.^2;
t3 = Il.*t2;
t4 = Im+t3;
t5 = 1.0./t4;
ddq_AF_u = reshape([0.0,0.0,0.0,t5,0.0,0.0,0.0,0.0,0.0,0.0,t5,0.0,0.0,0.0,0.0,0.0,0.0,t5],[6,3]);
end
