function E = energy_rimless_wheel_3_spoke(in1,in2)
%ENERGY_RIMLESS_WHEEL_3_SPOKE
%    E = ENERGY_RIMLESS_WHEEL_3_SPOKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

I = in2(3,:);
Il = in2(11,:);
Im = in2(12,:);
M = in2(1,:);
R = in2(10,:);
dpsiA = in1(10,:);
dpsiB = in1(11,:);
dpsiF = in1(12,:);
dth = in1(9,:);
dx = in1(7,:);
dy = in1(8,:);
g = in2(5,:);
ramp = in2(6,:);
x = in1(1,:);
y = in1(2,:);
t2 = R.^2;
t3 = dpsiA.^2;
t4 = dpsiB.^2;
t5 = dpsiF.^2;
E = (Im.*t3)./2.0+(Im.*t4)./2.0+(Im.*t5)./2.0+(I.*dth.^2)./2.0+(M.*(dx.^2+dy.^2))./2.0+(Il.*t2.*t3)./2.0+(Il.*t2.*t4)./2.0+(Il.*t2.*t5)./2.0+M.*g.*(y.*cos(ramp)-x.*sin(ramp));
end
