function out1 = jacobian_C_rimless_wheel_3_spoke(in1,in2)
%jacobian_C_rimless_wheel_3_spoke
%    OUT1 = jacobian_C_rimless_wheel_3_spoke(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

l = in2(4,:);
l0 = in2(8,:);
th = in1(3,:);
t2 = l+l0;
t3 = pi.*(2.0./3.0);
t4 = t3+th;
out1 = reshape([1.0,0.0,0.0,1.0,t2.*cos(t4),t2.*sin(t4),0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
end
