function out1 = jacobian_A_rimless_wheel_3_spoke(in1,in2)
%jacobian_A_rimless_wheel_3_spoke
%    OUT1 = jacobian_A_rimless_wheel_3_spoke(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

R = in2(10,:);
l = in2(4,:);
l0 = in2(8,:);
psiA = in1(4,:);
r = in2(9,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = R.*psiA.*r;
t5 = l+l0+t4;
out1 = reshape([1.0,0.0,0.0,1.0,t2.*t5,t3.*t5,R.*r.*t3,-R.*r.*t2,0.0,0.0,0.0,0.0],[2,6]);
end
