function keypoints = keypoints_rimless_wheel_3_spoke(in1,in2)
%KEYPOINTS_RIMLESS_WHEEL_3_SPOKE
%    KEYPOINTS = KEYPOINTS_RIMLESS_WHEEL_3_SPOKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

R = in2(10,:);
l = in2(4,:);
l0 = in2(8,:);
psiA = in1(4,:);
psiB = in1(5,:);
psiF = in1(6,:);
r = in2(9,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = l+l0;
t5 = R.*psiA.*r;
t6 = R.*psiB.*r;
t7 = R.*psiF.*r;
t8 = pi./3.0;
t9 = pi.*(2.0./3.0);
t10 = pi.*(4.0./3.0);
t11 = pi.*(5.0./3.0);
t12 = t8+th;
t13 = t9+th;
t14 = t10+th;
t15 = t11+th;
t16 = t4+t5;
t17 = t4+t6;
t18 = t4+t7;
keypoints = reshape([x+t3.*t16,y-t2.*t16,x+t17.*sin(t12),y-t17.*cos(t12),x+t4.*sin(t13),y-t4.*cos(t13),x-t3.*t4,y+t2.*t4,x+t4.*sin(t14),y-t4.*cos(t14),x+t18.*sin(t15),y-t18.*cos(t15)],[2,6]);
end
