function keypoints_vel = keypoints_vel_rimless_wheel_3_spoke(in1,in2)
%KEYPOINTS_VEL_RIMLESS_WHEEL_3_SPOKE
%    KEYPOINTS_VEL = KEYPOINTS_VEL_RIMLESS_WHEEL_3_SPOKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

R = in2(10,:);
dpsiA = in1(10,:);
dpsiB = in1(11,:);
dpsiF = in1(12,:);
dth = in1(9,:);
dx = in1(7,:);
dy = in1(8,:);
l = in2(4,:);
l0 = in2(8,:);
psiA = in1(4,:);
psiB = in1(5,:);
psiF = in1(6,:);
r = in2(9,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = l+l0;
t5 = R.*psiA.*r;
t6 = R.*psiB.*r;
t7 = R.*psiF.*r;
t8 = pi./3.0;
t9 = pi.*(2.0./3.0);
t10 = pi.*(4.0./3.0);
t11 = pi.*(5.0./3.0);
t12 = t8+th;
t13 = t9+th;
t14 = t10+th;
t15 = t11+th;
t16 = t4+t5;
t17 = t4+t6;
t18 = t4+t7;
t19 = cos(t12);
t20 = cos(t15);
t21 = sin(t12);
t22 = sin(t15);
keypoints_vel = reshape([dx+dth.*t2.*t16+R.*dpsiA.*r.*t3,dy+dth.*t3.*t16-R.*dpsiA.*r.*t2,dx+dth.*t17.*t19+R.*dpsiB.*r.*t21,dy+dth.*t17.*t21-R.*dpsiB.*r.*t19,dx+dth.*t4.*cos(t13),dy+dth.*t4.*sin(t13),dx-dth.*t2.*t4,dy-dth.*t3.*t4,dx+dth.*t4.*cos(t14),dy+dth.*t4.*sin(t14),dx+dth.*t18.*t20+R.*dpsiF.*r.*t22,dy+dth.*t18.*t22-R.*dpsiF.*r.*t20],[2,6]);
end
