function keypoints_spokes = keypoints_spokes_rimless_wheel_3_spoke(in1,in2)
%KEYPOINTS_SPOKES_RIMLESS_WHEEL_3_SPOKE
%    KEYPOINTS_SPOKES = KEYPOINTS_SPOKES_RIMLESS_WHEEL_3_SPOKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-May-2025 14:54:24

l = in2(4,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t6 = pi./3.0;
t7 = pi.*(2.0./3.0);
t8 = pi.*(4.0./3.0);
t9 = pi.*(5.0./3.0);
t4 = l.*t2;
t5 = l.*t3;
t10 = t6+th;
t11 = t7+th;
t12 = t8+th;
t13 = t9+th;
keypoints_spokes = reshape([t5+x,-t4+y,x+l.*sin(t10),y-l.*cos(t10),x+l.*sin(t11),y-l.*cos(t11),-t5+x,t4+y,x+l.*sin(t12),y-l.*cos(t12),x+l.*sin(t13),y-l.*cos(t13)],[2,6]);
end
