function A = A_cartpole(in1,in2)
%A_cartpole
%    A = A_cartpole(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Sep-2025 17:00:20

l = in2(3,:);
mC = in2(2,:);
mP = in2(1,:);
th = in1(2,:);
t2 = cos(th);
t3 = l.*mP.*t2;
t4 = -t3;
A = reshape([mC+mP,t4,t4,l.^2.*mP],[2,2]);
end
