function keypoints_vel = keypoints_vel_cartpole(in1,in2)
%KEYPOINTS_VEL_CARTPOLE
%    KEYPOINTS_VEL = KEYPOINTS_VEL_CARTPOLE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Sep-2025 17:00:20

dth = in1(4,:);
dx = in1(3,:);
l = in2(3,:);
th = in1(2,:);
keypoints_vel = reshape([dx,0.0,dx-dth.*l.*cos(th),-dth.*l.*sin(th)],[2,2]);
end
