function b = b_rimless_wheel_mass(in1,in2)
%B_RIMLESS_WHEEL_MASS
%    B = B_RIMLESS_WHEEL_MASS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Apr-2025 15:02:44

M = in2(1,:);
g = in2(5,:);
ramp = in2(6,:);
b = [M.*g.*sin(ramp);-M.*g.*cos(ramp);0.0;0.0;0.0;0.0;0.0;0.0;0.0];
end
