function E = energy_rimless_wheel_mass(in1,in2)
%ENERGY_RIMLESS_WHEEL_MASS
%    E = ENERGY_RIMLESS_WHEEL_MASS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Apr-2025 15:02:45

I = in2(3,:);
Il = in2(11,:);
Im = in2(12,:);
M = in2(1,:);
R = in2(10,:);
dpsiA = in1(13,:);
dpsiB = in1(14,:);
dpsiC = in1(15,:);
dpsiD = in1(16,:);
dpsiE = in1(17,:);
dpsiF = in1(18,:);
dth = in1(12,:);
dx = in1(10,:);
dy = in1(11,:);
g = in2(5,:);
ramp = in2(6,:);
x = in1(1,:);
y = in1(2,:);
t2 = R.^2;
t3 = dpsiA.^2;
t4 = dpsiB.^2;
t5 = dpsiC.^2;
t6 = dpsiD.^2;
t7 = dpsiE.^2;
t8 = dpsiF.^2;
E = (Im.*t3)./2.0+(Im.*t4)./2.0+(Im.*t5)./2.0+(Im.*t6)./2.0+(Im.*t7)./2.0+(Im.*t8)./2.0+(I.*dth.^2)./2.0+(M.*(dx.^2+dy.^2))./2.0+(Il.*t2.*t3)./2.0+(Il.*t2.*t4)./2.0+(Il.*t2.*t5)./2.0+(Il.*t2.*t6)./2.0+(Il.*t2.*t7)./2.0+(Il.*t2.*t8)./2.0+M.*g.*(y.*cos(ramp)-x.*sin(ramp));
end
