function out1 = jacobian_D_rimless_wheel_mass(in1,in2)
%jacobian_D_rimless_wheel_mass
%    OUT1 = jacobian_D_rimless_wheel_mass(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Apr-2025 15:02:45

R = in2(10,:);
l = in2(4,:);
l0 = in2(8,:);
psiD = in1(7,:);
r = in2(9,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = R.*psiD.*r;
t5 = l+l0+t4;
out1 = reshape([1.0,0.0,0.0,1.0,-t2.*t5,-t3.*t5,0.0,0.0,0.0,0.0,0.0,0.0,-R.*r.*t3,R.*r.*t2,0.0,0.0,0.0,0.0],[2,9]);
end
