function out1 = jacobian_B_rimless_wheel_mass(in1,in2)
%jacobian_B_rimless_wheel_mass
%    OUT1 = jacobian_B_rimless_wheel_mass(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Apr-2025 15:02:45

R = in2(10,:);
l = in2(4,:);
l0 = in2(8,:);
psiB = in1(5,:);
r = in2(9,:);
th = in1(3,:);
t2 = R.*psiB.*r;
t3 = pi./3.0;
t4 = t3+th;
t5 = l+l0+t2;
t6 = cos(t4);
t7 = sin(t4);
out1 = reshape([1.0,0.0,0.0,1.0,t5.*t6,t5.*t7,0.0,0.0,R.*r.*t7,-R.*r.*t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,9]);
end
