function keypoints = keypoints_rimless_wheel_mass(in1,in2)
%KEYPOINTS_RIMLESS_WHEEL_MASS
%    KEYPOINTS = KEYPOINTS_RIMLESS_WHEEL_MASS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Apr-2025 15:02:45

R = in2(10,:);
l = in2(4,:);
l0 = in2(8,:);
psiA = in1(4,:);
psiB = in1(5,:);
psiC = in1(6,:);
psiD = in1(7,:);
psiE = in1(8,:);
psiF = in1(9,:);
r = in2(9,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = R.*psiA.*r;
t5 = R.*psiB.*r;
t6 = R.*psiC.*r;
t7 = R.*psiD.*r;
t8 = R.*psiE.*r;
t9 = R.*psiF.*r;
t10 = pi./3.0;
t11 = pi.*(2.0./3.0);
t12 = pi.*(4.0./3.0);
t13 = pi.*(5.0./3.0);
t14 = t10+th;
t15 = t11+th;
t16 = t12+th;
t17 = t13+th;
t18 = l+l0+t4;
t19 = l+l0+t5;
t20 = l+l0+t6;
t21 = l+l0+t7;
t22 = l+l0+t8;
t23 = l+l0+t9;
keypoints = reshape([x+t3.*t18,y-t2.*t18,x+t19.*sin(t14),y-t19.*cos(t14),x+t20.*sin(t15),y-t20.*cos(t15),x-t3.*t21,y+t2.*t21,x+t22.*sin(t16),y-t22.*cos(t16),x+t23.*sin(t17),y-t23.*cos(t17)],[2,6]);
end
