function keypoints_vel = keypoints_vel_rimless_wheel_mass(in1,in2)
%KEYPOINTS_VEL_RIMLESS_WHEEL_MASS
%    KEYPOINTS_VEL = KEYPOINTS_VEL_RIMLESS_WHEEL_MASS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Apr-2025 15:02:45

R = in2(10,:);
dpsiA = in1(13,:);
dpsiB = in1(14,:);
dpsiC = in1(15,:);
dpsiD = in1(16,:);
dpsiE = in1(17,:);
dpsiF = in1(18,:);
dth = in1(12,:);
dx = in1(10,:);
dy = in1(11,:);
l = in2(4,:);
l0 = in2(8,:);
psiA = in1(4,:);
psiB = in1(5,:);
psiC = in1(6,:);
psiD = in1(7,:);
psiE = in1(8,:);
psiF = in1(9,:);
r = in2(9,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = R.*psiA.*r;
t5 = R.*psiB.*r;
t6 = R.*psiC.*r;
t7 = R.*psiD.*r;
t8 = R.*psiE.*r;
t9 = R.*psiF.*r;
t10 = pi./3.0;
t11 = pi.*(2.0./3.0);
t12 = pi.*(4.0./3.0);
t13 = pi.*(5.0./3.0);
t14 = t10+th;
t15 = t11+th;
t16 = t12+th;
t17 = t13+th;
t18 = l+l0+t4;
t19 = l+l0+t5;
t20 = l+l0+t6;
t21 = l+l0+t7;
t22 = l+l0+t8;
t23 = l+l0+t9;
t24 = cos(t14);
t25 = cos(t15);
t26 = cos(t16);
t27 = cos(t17);
t28 = sin(t14);
t29 = sin(t15);
t30 = sin(t16);
t31 = sin(t17);
keypoints_vel = reshape([dx+dth.*t2.*t18+R.*dpsiA.*r.*t3,dy+dth.*t3.*t18-R.*dpsiA.*r.*t2,dx+dth.*t19.*t24+R.*dpsiB.*r.*t28,dy+dth.*t19.*t28-R.*dpsiB.*r.*t24,dx+dth.*t20.*t25+R.*dpsiC.*r.*t29,dy+dth.*t20.*t29-R.*dpsiC.*r.*t25,dx-dth.*t2.*t21-R.*dpsiD.*r.*t3,dy-dth.*t3.*t21+R.*dpsiD.*r.*t2,dx+dth.*t22.*t26+R.*dpsiE.*r.*t30,dy+dth.*t22.*t30-R.*dpsiE.*r.*t26,dx+dth.*t23.*t27+R.*dpsiF.*r.*t31,dy+dth.*t23.*t31-R.*dpsiF.*r.*t27],[2,6]);
end
